name: Daily run_all.py

on:
  schedule:
    # Runs every day at 2:30 AM Pacific (09:30 UTC)
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    # expose your secret as an env var
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-geckodriver firefox

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK punkt
        run: |
          python - <<EOF
          import nltk; nltk.download('punkt')
          EOF

      - name: Run run_all.py
        run: python run_all.py

      - name: Commit & push generated files
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update auto-generated files"
            git push
          else
            echo "No changes to commit"
          fi
