name: Daily run_all.py

on:
  schedule:
    # Runs every day at 2:30 AM Pacific (UTC–7 → 09:30 UTC)
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        # for Selenium + Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-geckodriver firefox

      - name: Install Python dependencies
        # Assumes you have a requirements.txt at repo root
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK punkt
        run: |
          python - <<EOF
          import nltk; nltk.download('punkt')
          EOF

      - name: Run run_all.py
        run: python run_all.py

      - name: Commit & push generated files
        if: success() # Only run if the above steps succeeded
        run: |
          # Configure Git for Actions bot
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage all changes (new, modified, deleted files)
          git add -A

          # If there is anything to commit, do so
          if ! git diff --cached --quiet; then
            git commit -m "chore: update auto-generated files"
            git push
          else
            echo "No changes to commit"
          fi
