name: Daily run_all.py

permissions:
  contents: write # grant write access for GITHUB_TOKEN

on:
  schedule:
    # Runs every day at 2:30 AM Pacific (09:30 UTC)
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true # so git push uses the GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ───── Install Python dependencies ─────
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ───── Download NLTK punkt data ─────
      - name: Download NLTK data
        run: |
          python - <<EOF
          import nltk
          nltk.download('punkt')
          nltk.download('punkt_tab')
          EOF

      # ───── Run your pipeline under Xvfb ─────
      - name: Run run_all.py
        run: xvfb-run --auto-servernum python run_all.py

      # ───── Commit & push generated files ─────
      - name: Commit & push generated files
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update auto-generated files"
            git push
          else
            echo "No changes to commit"
          fi
